# Generated by Django 3.0.6 on 2020-05-23 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('deptno', models.IntegerField(primary_key=True, serialize=False)),
                ('dname', models.CharField(max_length=14)),
                ('loc', models.CharField(max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('empno', models.IntegerField(primary_key=True, serialize=False)),
                ('ename', models.CharField(max_length=20)),
                ('job', models.CharField(max_length=9)),
                ('hiredate', models.DateField()),
                ('sal', models.FloatField()),
                ('comm', models.FloatField()),
                ('deptno', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lab.Dept')),
                ('mgr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.Emp')),
            ],
        ),
    ]
