# Generated by Django 3.0.6 on 2020-05-23 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='mgr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lab.Emp'),
        ),
    ]
