# Generated by Django 3.0.6 on 2020-05-23 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0003_auto_20200523_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='deptno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lab.Dept'),
        ),
        migrations.AlterField(
            model_name='emp',
            name='mgr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lab.Emp'),
        ),
    ]
